export const products = [
  { value: 186491, label: 'Cardio-Sei', path: 'products/default-product.webp' },
  { value: 192001, label: 'Eropower', path: 'products/default-product.webp' },
  { value: 192114, label: 'ARTICULINE', path: 'products/default-product.webp' },
  { value: 193976, label: 'Cardio-Sei Varikoz', path: 'products/default-product.webp' },
  { value: 196548, label: 'BE CLEAN', path: 'products/default-product.webp' },
  { value: 198508, label: 'Prostrong', path: 'products/default-product.webp' },
  { value: 199030, label: 'Femiston', path: 'products/default-product.webp' },
  { value: 202690, label: 'ManBalance', path: 'products/man-balance.webp' },
  { value: 202914, label: 'FlexBalance', path: 'products/flex-balance.webp' },
  { value: 204116, label: 'BodyBalance', path: 'products/body-balance.webp' },
  { value: 204117, label: 'EroKing', path: 'products/ero-king.webp' },
  { value: 204118, label: 'AlcoBalance', path: 'products/alco-balance.webp' },
  { value: 204119, label: 'FemBalance', path: 'products/fem-balance.webp' },
  { value: 204120, label: 'LibidoFortis', path: 'products/libido-fortis.webp' },
];
